INSERT INTO puerto (direccion) VALUES
                                   ('Calle del Muelle 1, Puerto de Barcelona'),
                                   ('Avenida Marítima 45, Puerto de Valencia'),
                                   ('Plaza del Puerto 12, Puerto de Málaga'),
                                   ('Paseo Marítimo 88, Puerto de Sevilla'),
                                   ('Ronda del Mar 23, Puerto de Bilbao'),
                                   ('Avenida Portuaria 67, Puerto de Vigo'),
                                   ('Calle Náutica 15, Puerto de Las Palmas'),
                                   ('Boulevard Costero 42, Puerto de Cádiz'),
                                   ('Paseo del Atlántico 99, Puerto de A Coruña'),
                                   ('Avenida del Mediterráneo 5, Puerto de Alicante');

INSERT INTO barco (nombre, usuario, id_puerto) VALUES
                                                   ('Marinero Errante', 'capitanperez', 1),
                                                   ('Estrella del Mar', 'juan_garcia', 1),
                                                   ('Viento del Norte', 'maricarmen23', 2),
                                                   ('Horizonte Azul', 'robertomartinez', 3),
                                                   ('Ola Perfecta', 'anasanchez', 2),
                                                   ('Neptuno I', 'carlosruiz', 4),
                                                   ('Aurora Marina', 'lucia_fernandez', 3),
                                                   ('Delfín Veloz', 'pedrolopez', 1),
                                                   ('Sirena Dorada', 'miguelangel', 5),
                                                   ('Tritón Salvaje', 'carmen_lopez', 6),
                                                   ('Brisa del Sur', 'francisco_martin', 4),
                                                   ('Poseidón II', 'marta_sanchez', 7),
                                                   ('Gaviota Real', 'antonio_ruiz', 2),
                                                   ('Coral Azul', 'isabel_garcia', 8),
                                                   ('Albatros Negro', 'jose_fernandez', 5),
                                                   ('Marejada Alta', 'laura_martinez', 9),
                                                   ('Velero Fantasma', 'davidjimenez', 3),
                                                   ('Tormenta Blanca', 'raquel_perez', 10),
                                                   ('Golondrina Marina', 'alberto_gomez', 6),
                                                   ('Pez Espada', 'beatriz_lopez', 1),
                                                   ('Navegante Solitario', 'sergio_hernandez', 7),
                                                   ('Luna Plateada', 'patricia_diaz', 4),
                                                   ('Kraken Azul', 'manuel_alvarez', 8),
                                                   ('Carabela Santa María', 'cristina_romero', 9),
                                                   ('Tiburón Blanco', 'javier_torres', 10),
                                                   ('Orca del Pacífico', 'elena_ramirez', 2),
                                                   ('Faro del Oeste', 'pablo_moreno', 5),
                                                   ('Ancla de Oro', 'monica_muñoz', 3),
                                                   ('Capitán Nemo', 'rafael_iglesias', 6),
                                                   ('Perla Negra', 'silvia_castro', 10);
